
'''
The sequence of triangle numbers is generated by adding the natural numbers.
So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

    1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

         1: 1
          3: 1,3
           6: 1,2,3,6
           10: 1,2,5,10
           15: 1,3,5,15
           21: 1,3,7,21
           28: 1,2,4,7,14,28
We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?

'''

import math

def no_of_divisiors(n):
    large_divisors = []
    for i in range(1, int(math.sqrt(n) + 1)):
        if n % i == 0:
            yield i
            if i * i != n:
                large_divisors.append(n // i)
    for divisor in reversed(large_divisors):
        yield divisor

def all_triangle_nos(n):
    prev_num = 0
    l = []
    for i in range(1, n+1):
        l.append(i + prev_num)
        prev_num += i
    return l

def main():
    i = 1
    while len(list(no_of_divisiors(all_triangle_nos(i)[-1]))) < 500:
        i += 1
    print(all_triangle_nos(i)[-1])


if __name__ == "__main__":
    # print(list(no_of_divisiors(int(sys.argv[1]))))
    # print(all_triangle_nos(7))
    main()
